# Generated by Django 2.0.6 on 2018-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='recipe',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='formmodel',
            old_name='dateCreated',
            new_name='established_date',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='timeCook',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formmodel',
            name='operating_budget',
            field=models.IntegerField(default=0),
        ),
    ]
