# Generated by Django 2.0.6 on 2018-10-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_auto_20181016_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
