# Generated by Django 2.0.6 on 2018-10-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_formmodel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
