# Generated by Django 2.0.6 on 2018-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_formmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=500)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
