# Generated by Django 2.0.6 on 2018-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_contactmemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmemodel',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
